# file-portal k8s deployment
---
apiVersion: v1
kind: Service
metadata:
  name: file-portal
  labels:
    app: file-portal
spec:
  ports:
  - name: http
    protocol: TCP
    port: 8081                                    # service对外提供服务的端口
    targetPort: 8081
    nodePort: 8081
  type: NodePort
  selector:
    app: file-portal
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: file-portal
  labels:
    app: file-portal
spec:
  replicas: 2
  selector:
    matchLabels:
      app: file-portal
  template:
    metadata:
      labels:
        app: file-portal
    spec:
      containers:
      - name: file-portal
        image: registry.cn-hangzhou.aliyuncs.com/zakiis/file-portal:0.0.5
        ports:
        - containerPort: 8081
        resources:
          limits:
            cpu: "2"
            memory: 1.5Gi
          requests:
            cpu: 500m
            memory: 512Mi
        readinessProbe:
          httpGet:
            path: /health
            port: 8081
            scheme: HTTP
          initialDelaySeconds: 20
          periodSeconds: 5
          failureThreshold: 3
          successThreshold: 1
        livenessProbe:
          tcpSocket: 
             port: 8081
          initialDelaySeconds: 25
          periodSeconds: 3
          failureThreshold: 3
          successThreshold: 1
        env:
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: APP_TIMEZONE
          value: GMT+8
        volumeMounts:
        - mountPath: /wls/deploy/logs
          name: logs
          subPathExpr: $(POD_NAME)
      initContainers: #先在宿主机初始化目录：mkdir -p /data/logs && groupadd -g 1001 -r wls && useradd -r -g 1001 -u 1001 wls81 && chown wls81:wls /data/logs/
      - name: init-logdir
        image: registry.cn-hangzhou.aliyuncs.com/zakiis/file-portal:0.0.5
        command: ['sh', '-c', 'mkdir -p /wls/deploy/logs/${POD_NAME}']
        env:
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        volumeMounts:
        - mountPath: /wls/deploy/logs
          name: logs
      volumes: 
      - name: logs
        hostPath: 
          path: /data/logs
          type: Directory
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata: 
  name: file-portal
spec: 
  scaleTargetRef: 
    apiVersion: apps/v1
    kind: Deployment
    name: file-portal
  minReplicas: 2
  maxReplicas: 5
  targetCPUUtilizationPercentage: 70